### PR TITLE
feat: support smartmode params

### PR DESCRIPTION
**Pull request by barlock**
In support of: https://github.com/mikelawrence/senseme-hacs/issues/33

Adds support for setting and reading smartmode parameters

### CODE REVIEW

**Comment by mikelawrence** [comment]
coolminspeed range is 0-6 not 0-7.
coolmaxspeed range is 1-7 not 0-7.

**Comment by mikelawrence** [comment]
I find it interesting that when auto comfort is set to cooling and you manually set the fan speed to something outside the range of coolminspeed or coolmaxspeed, coolminspeed will track the fan speed when lower and coolmaxspeed will track the fan speed when above.

**Comment by barlock** [comment]
Bump here in case you didn't see that I fixed your comments. If you're still busy, no worries, been running this fine from my fork.

**Comment by spf13** [comment]
I'd really like to use this functionality and understand that @mikelawrence isn't active right now. 

Is there an easy way to use @barlock's fork from home assistant? I've been searching in the docs and via Google and I'm not seeing any way to do this without uninstalling the integration and then installing from another source, but doing that would require removing all my integrations. 

Or alternatively would @mikelawrence be willing to add @barlock as a maintainer to help move this project forward a bit?

I'm happy to help with the occasional review if that helps.

**Comment by barlock** [comment]
I would happily accept a maintainership. 

You can use my fork in home assistant by setting up my fork of senseme-hacs as a custom repo in hacks https://github.com/barlock/senseme-hacs. I've been using it happily ever since I made the PRs.

**Comment by spf13** [comment]
I tried that approach and if I remember correctly it wanted me to remove
the mikelawrence one first, which meant removing all of my devices and
setting them all up again.
Is there a way to do that without removing the mikelawrence one first?

**Comment by bdraco** [comment]
Thanks @barlock 👍

**Pull request merged**
